<?xml version="1.0" encoding="UTF-8"?>
<!--
資料名稱: 臺灣出版新書預告書訊
收錄期間: 本資料與全國新書資訊網「書目下載/批次下載」每月同步更新，本次更新申請日期: 20170101~20170131 區間的資料。
說　　明: 本資料集內容屬我國即將出版之新書，向國家圖書館國際標準書號中心申請國際標準書號（ISBN）之新書書目資訊。正式出版後時有異動，請以正式出版之書目資料為準。
-->
<!DOCTYPE Book [
<!ELEMENT Book (書名, 作者, 出版單位, 版次, 出版年月, 標題, 適讀對象, 類號, ISBN)>
<!ELEMENT 書名 (#PCDATA)>
<!ELEMENT 作者 (#PCDATA)>
<!ELEMENT 出版單位 (#PCDATA)>
<!ELEMENT 版次 (#PCDATA)>
<!ELEMENT 出版年月 (#PCDATA)>
<!ELEMENT 標題 (#PCDATA)>
<!ELEMENT 適讀對象 (#PCDATA)>
<!ELEMENT 類號 (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
]>
<Books>
	<Book>
		<書名>成功好運勢,幸運好運勢&lt;&lt;上篇&gt;&gt;Succeed Fortune, Lucky Fortune: 有錢人會創造自己的好運勢,財富跟著來,掀開「成功好運勢」和「幸運好運勢」自己創造的神秘面紗</書名>
		<作者>柳延蓉著</作者>
		<出版單位>勢一文化</出版單位>
		<版次></版次>
		<出版年月>106/03</出版年月>
		<標題>1.信仰 2.成功法</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>177.2</類號>
		<ISBN>978-986-93480-0-3 (精裝, 380面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>成功好運勢,幸運好運勢&lt;&lt;中篇&gt;&gt;Succeed Fortune、Lucky Fortune: 「成功好運勢｣來自自我實現</書名>
		<作者>柳延蓉著</作者>
		<出版單位>勢一文化</出版單位>
		<版次></版次>
		<出版年月>106/03</出版年月>
		<標題>1.自我實現 2.食物治療</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>177.2</類號>
		<ISBN>978-986-93480-1-0 (精裝, 380面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>成功好運勢,幸運好運勢&lt;&lt;下篇&gt;&gt;Succeed Fortune、Lucky Fortune: 「成功好運勢｣來自後天努力</書名>
		<作者>柳延蓉著</作者>
		<出版單位>勢一文化</出版單位>
		<版次></版次>
		<出版年月>106/03</出版年月>
		<標題>1.法律教育 2.經濟發展</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>177.2</類號>
		<ISBN>978-986-93480-2-7 (精裝, 250面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>我們都是一家人: 我們一起寫榮民</書名>
		<作者>高瑞芳等作; 國軍退除役官兵輔導委員會行政管理處編</作者>
		<出版單位>輔導會</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題>1.退役軍人 2.文集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>594.7907</類號>
		<ISBN>978-986-05-1668-5 (平裝, NT$250, 122面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>動物的內心生活</書名>
		<作者>彼得.渥雷本(Peter Wohlleben)著; 鐘寶珍譯</作者>
		<出版單位>商周</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.動物心理學 2.動物行為</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>383.7</類號>
		<ISBN>978-986-477-182-0 (平裝, NT$360, 320面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>青穗: 專輯研究論文集. 第二十六屆</書名>
		<作者>俞柏安等作</作者>
		<出版單位>北市西湖國小資優班</出版單位>
		<版次></版次>
		<出版年月>105/12</出版年月>
		<標題>1.小學教學 2.文集</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>523.307</類號>
		<ISBN>978-986-05-1680-7 (平裝, 380面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>公民參與的框架與擴散: 法、德、英的參與式預算</書名>
		<作者>Anja Röcke著; 白舜羽譯</作者>
		<出版單位>國家教育研究院</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.政府預算 2.預算監督 3.文集</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>564.3507</類號>
		<ISBN>978-986-05-1681-4 (平裝, NT$280, 215面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>女農: 12位農漁業女性工作者從業經驗訪談</書名>
		<作者>張麗玲, 吳雅雯文稿撰寫</作者>
		<出版單位>農委會</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.農民 2.女性傳記</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>431.4</類號>
		<ISBN>978-986-05-1682-1 (平裝, NT$250, 86面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>臺灣鳳邑儒教聯堂的飛鸞勸化與其社會網絡</書名>
		<作者>邱延洲作</作者>
		<出版單位>高市史博館</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題>1.民間信仰 2.宗教與社會 3.臺灣</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>733.08</類號>
		<ISBN>978-986-05-1683-8 (平裝, NT$320, 288面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>延續與變遷: 遷村後紅毛港的寺廟與信仰</書名>
		<作者>謝貴文作</作者>
		<出版單位>高市史博館</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題>1.寺廟 2.民間信仰 3.宗教與社會 4.臺灣</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>733.08</類號>
		<ISBN>978-986-05-1684-5 (平裝, NT$300, 140面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>孔邁隆教授美濃與客家研究論集</書名>
		<作者>孔邁隆(Myron L. Cohen)作; 黃宣衛, 劉容貴譯</作者>
		<出版單位>高市史博館</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題>1.民族研究 2.家庭 3.客家 4.Ethnology 5.Families 6.臺灣 7.Taiwan</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>733.08</類號>
		<ISBN>978-986-05-1686-9 (上冊:平裝, NT$300, 400面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>精通SolidWorks 2016. 基礎篇</書名>
		<作者>陳俊鴻作</作者>
		<出版單位>經瑋文化</出版單位>
		<版次>二版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.SolidWorks(電腦程式) 2.電腦繪圖</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>312.49S678</類號>
		<ISBN>978-986-94095-7-5 (平裝, 552面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>誰都會做的超好玩感測機器人</書名>
		<作者>熊谷文宏著; 陳曉峯譯</作者>
		<出版單位>泰電電業</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.機器人</標題>
		<適讀對象>青少年</適讀對象>
		<類號>448.992</類號>
		<ISBN>978-986-405-036-9 (平裝, NT$300, 296面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>臺灣中小企業轉型至循環經濟的挑戰與契機</書名>
		<作者>余騰耀主編</作者>
		<出版單位>中技社</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題>1.產業政策 2.產業發展 3.綠色企業</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>555.933</類號>
		<ISBN>978-986-92691-7-9 (平裝, 104面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>工具機切削技術研究</書名>
		<作者>周國華著</作者>
		<出版單位>翰蘆圖書</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.工具機</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>446.841</類號>
		<ISBN>978-986-5860-99-8 (平裝, NT$700, 368面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>圖解相對論!愛因斯坦教會我們什麼?: 輕鬆搞懂20世紀最偉大的科學理論</書名>
		<作者>新堂進著; 陳威丞譯</作者>
		<出版單位>臺灣廣廈</出版單位>
		<版次></版次>
		<出版年月>106/03</出版年月>
		<標題>1.相對論</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>331.2</類號>
		<ISBN>978-986-130-352-9 (平裝, NT$280, 208面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>歡迎來到夜谷</書名>
		<作者>約瑟夫.芬克(Joseph Fink), 傑佛瑞.克雷諾(Jeffery Cranor)著; 林曉欽譯</作者>
		<出版單位>獨步文化</出版單位>
		<版次></版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>874.57</類號>
		<ISBN>978-986-5651-87-9 (平裝, NT$380, 368面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>悲慘世界經典全譯本</書名>
		<作者>維克多.雨果著; 李玉民譯</作者>
		<出版單位>野人文化</出版單位>
		<版次>再版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>876.57</類號>
		<ISBN>978-986-384-185-2 (精裝, 928面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>亞洲藝術</書名>
		<作者>高木森著</作者>
		<出版單位>東大</出版單位>
		<版次>二版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.藝術史 2.亞洲</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>909.3</類號>
		<ISBN>978-957-19-3140-1 (平裝, 422面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>不需要,就是九成煩惱的解藥</書名>
		<作者>何權峰作</作者>
		<出版單位>高寶國際</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.修身 2.生活指導</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>192.1</類號>
		<ISBN>978-986-361-381-7 (平裝, 224面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>了義海: 俱生和合甚深教導: 了義海心髓之光耀事業</書名>
		<作者>第九世法王噶瑪巴旺秋多傑作; 施心慧譯</作者>
		<出版單位>化育文教基金會</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.藏傳佛教 2.佛教修持</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>226.965</類號>
		<ISBN>978-986-90068-7-3 (精裝, 576面, 22公分)</ISBN>
	</Book>
	<Book>
		<書名>將門金枝</書名>
		<作者>面北眉南著; 雨沫上青繪</作者>
		<出版單位>可橙文化工坊</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-93767-5-4 (卷3:平裝, NT$250, 400面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>漁港的肉子</書名>
		<作者>西加奈子著; 林佩瑾譯</作者>
		<出版單位>圓神</出版單位>
		<版次>初版</版次>
		<出版年月>106/03</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>861.57</類號>
		<ISBN>978-986-133-607-7 (平裝, NT$300, 272面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>行銷學概要</書名>
		<作者>李培齊, 蔡政言, 孫嘉祈作</作者>
		<出版單位>滄海</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.行銷學</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>496</類號>
		<ISBN>978-986-363-032-6 (平裝, 424面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>沉香救母: 神話故事</書名>
		<作者>任發權作</作者>
		<出版單位>八八</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>539.581</類號>
		<ISBN>978-986-91698-3-7 (平裝, 391面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>愛人: 歐崇敬詩集. 1</書名>
		<作者>歐崇敬著</作者>
		<出版單位>停雲</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>851.486</類號>
		<ISBN>978-986-92964-5-8 (平裝, NT$260, 135面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>熵翳學</書名>
		<作者>沈博文作</作者>
		<出版單位>城邦印書館</出版單位>
		<版次></版次>
		<出版年月>106/01</出版年月>
		<標題>1.靈修 2.生物能量學</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>192.1</類號>
		<ISBN>978-986-94107-5-5 (精裝, NT$580, 208面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>靈鷲山弘法紀要. 2016</書名>
		<作者>釋法昂等編輯</作者>
		<出版單位>靈鷲山般若出版</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.佛教教化法 2.佛教說法</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>225.4</類號>
		<ISBN>978-986-93650-4-8 (平裝, NT$580, 180面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>蔣廷黻與蔣介石</書名>
		<作者>湯晏著</作者>
		<出版單位>大塊文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.蔣廷黻 2.傳記</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>782.886</類號>
		<ISBN>978-986-213-777-2 (平裝, NT$500, 486面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>大慈恩寺三藏法師傳</書名>
		<作者>(唐)沙門慧立撰; 彥悰箋</作者>
		<出版單位>北市大乘基金會</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題>1.釋玄奘 2.佛教傳記</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>229.34</類號>
		<ISBN>978-986-5963-72-9 (平裝, 432面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>意義的呼喚: 意義治療大師法蘭可自傳(二十週年紀念版)</書名>
		<作者>維克多.法蘭可(Viktor E. Frankl)作; 鄭納無譯</作者>
		<出版單位>心靈工坊文化</出版單位>
		<版次>二版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.法蘭可(Frankl, Viktor E. (Viktor Emil), 1905-1997)) 2.Frankl,Viktor E 3.傳記 4.心理治療師 5.Psychoanalysts 6.Psychotherapists 7.Logotherapy</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>784.418</類號>
		<ISBN>978-986-357-085-1 (平裝, NT$320, 256面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>小樂秘密日記: 爸媽不要看</書名>
		<作者>陳怡璇文; 鄭玉佩圖</作者>
		<出版單位>康軒文教</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>859.7</類號>
		<ISBN>978-986-151-927-2 (第1冊:平裝, NT$250, 128面, 24公分)</ISBN>
	</Book>
	<Book>
		<書名>小樂秘密日記: 爸媽不要看</書名>
		<作者>陳怡璇文; 鄭玉佩圖</作者>
		<出版單位>康軒文教</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>859.7</類號>
		<ISBN>978-986-151-928-9 (第2冊:平裝, NT$250, 128面, 24公分)</ISBN>
	</Book>
	<Book>
		<書名>東亞戰略安全的三角習題</書名>
		<作者>陳俊昇著</作者>
		<出版單位>華立圖書</出版單位>
		<版次>一版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.戰略 2.外交政策 3.文集 4.東亞</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>592.493</類號>
		<ISBN>978-957-784-684-6 (平裝, NT$200, 200面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>余雪明講座教授的證券法學說</書名>
		<作者>鄭明德著</作者>
		<出版單位>華立圖書</出版單位>
		<版次>一版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.證券法規 2.論述分析</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>563.51</類號>
		<ISBN>978-957-784-685-3 (平裝, NT$200, 100面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>設計翻轉!用設計改變臺北: 臺北世界設計之都國際設計政策論壇. 2016</書名>
		<作者>臺灣創意設計中心, 天下雜誌股份有限公司執行編輯</作者>
		<出版單位>北市文化局</出版單位>
		<版次></版次>
		<出版年月>105/12</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-05-1689-0 (平裝附光碟片, 48面, 27公分)</ISBN>
	</Book>
	<Book>
		<書名>超質感場景繪製美學: 結合人與物的絕美背景電繪技法</書名>
		<作者>吳嘉芳著</作者>
		<出版單位>碁峰資訊</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.數位影像處理 2.電腦繪圖</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.837</類號>
		<ISBN>978-986-476-306-1 (平裝, 208面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>你所不知道的JS: ES6與未來發展</書名>
		<作者>Kyle Simpson原著; 黃銘偉譯</作者>
		<出版單位>碁峰資訊</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.Java Script(電腦程式語言)</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.32J36</類號>
		<ISBN>978-986-476-307-8 (平裝, 278面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>超清新水性色鉛筆隨手畫10000例大全: 療癒你的生活無極限</書名>
		<作者>飛樂鳥工作室著</作者>
		<出版單位>碁峰資訊</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.鉛筆畫 2.繪畫技法</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>948.2</類號>
		<ISBN>978-986-476-308-5 (平裝, 240面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>個案餘香: 個案管理服務案例. 2016</書名>
		<作者>臺北市就業服務處撰</作者>
		<出版單位>北市就業服務處</出版單位>
		<版次></版次>
		<出版年月>105/12</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-05-1690-6 (平裝, 45面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>助詞輕鬆學: 我的日語超厲害!</書名>
		<作者>舒博文作</作者>
		<出版單位>笛藤</出版單位>
		<版次>三版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.日語 2.助詞</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>803.167</類號>
		<ISBN>978-957-710-685-8 (平裝附光碟片, NT$300, 224面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>完勝大考英語7000單字: 中級篇2001-4500字</書名>
		<作者>空中英語教室編輯群著</作者>
		<出版單位>笛藤</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.英語教學 2.詞彙 3.中等教育</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>524.38</類號>
		<ISBN>978-957-710-686-5 (平裝, NT$300, 496面, 29公分)</ISBN>
	</Book>
	<Book>
		<書名>深入研究Hadoop 2.0-YARN核心技術</書名>
		<作者>周維著</作者>
		<出版單位>佳魁資訊</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.雲端運算 2.電子資料處理</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.136</類號>
		<ISBN>978-986-379-464-6 (平裝, NT$540, 288面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>輕鬆搞定: MAYA實用技法不NG</書名>
		<作者>夢德編著</作者>
		<出版單位>佳魁資訊</出版單位>
		<版次></版次>
		<出版年月>106/02</出版年月>
		<標題>1.MAYA(電腦程式) 2.電腦動畫</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>312.8</類號>
		<ISBN>978-986-379-465-3 (平裝, 208面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>Web應用程式開發の羽量級</書名>
		<作者>邱俊濤著</作者>
		<出版單位>佳魁資訊</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.全球資訊網 2.電腦程式 3.資料庫設計</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.1695</類號>
		<ISBN>978-986-379-466-0 (平裝, NT$540, 392面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>精靈鞋匠</書名>
		<作者>霍爾迪.帕萊特(Jordi Palet)作; 埃斯特爾.勞倫斯(Ester Llorens)繪; 劉舒暢譯</作者>
		<出版單位>東雨文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>878.59</類號>
		<ISBN>978-986-94304-3-2 (平裝, NT$500, 72面, 27公分)</ISBN>
	</Book>
	<Book>
		<書名>誰是我的公主?</書名>
		<作者>霍爾迪.帕萊特(Jordi Palet)作; 埃斯特爾.勞倫斯(Ester Llorens)繪; 劉舒暢譯</作者>
		<出版單位>東雨文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>878.59</類號>
		<ISBN>978-986-94304-4-9 (平裝, NT$500, 72面, 27公分)</ISBN>
	</Book>
	<Book>
		<書名>專門用來打好四則運算基礎的數學課本&lt;&lt;第3級&gt;&gt;</書名>
		<作者>財團法人博幼社會福利基金會著</作者>
		<出版單位>五南</出版單位>
		<版次>二版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.數學教育 2.算術 3.運算 4.小學教學</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>523.32</類號>
		<ISBN>978-957-11-9021-1 (平裝, NT$420, 304面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>專門用來打好四則運算基礎的數學課本&lt;&lt;第4級&gt;&gt;</書名>
		<作者>財團法人博幼社會福利基金會著</作者>
		<出版單位>五南</出版單位>
		<版次>三版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.數學教育 2.算術 3.運算 4.小學教學</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>523.32</類號>
		<ISBN>978-957-11-9022-8 (平裝, NT$360, 328面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>專門用來打好四則運算基礎的數學課本&lt;&lt;第5級&gt;&gt;</書名>
		<作者>財團法人博幼社會福利基金會著</作者>
		<出版單位>五南</出版單位>
		<版次>三版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.數學教育 2.算術 3.運算 4.小學教學</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>523.32</類號>
		<ISBN>978-957-11-9023-5 (平裝, NT$400, 316面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>天地明環</書名>
		<作者>黃易作</作者>
		<出版單位>蓋亞文化</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-319-263-3 (第16冊:平裝, NT$220, 224面, 20公分)</ISBN>
	</Book>
	<Book>
		<書名>天地明環</書名>
		<作者>黃易作</作者>
		<出版單位>蓋亞文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-319-264-0 (第17冊:平裝, NT$220, 224面, 20公分)</ISBN>
	</Book>
	<Book>
		<書名>天地明環</書名>
		<作者>黃易作</作者>
		<出版單位>蓋亞文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-319-265-7 (第18冊:平裝, NT$220, 224面, 20公分)</ISBN>
	</Book>
	<Book>
		<書名>找尋臺灣之光: 魯蛇轉型大補帖</書名>
		<作者>許介文著</作者>
		<出版單位>獨立作家</出版單位>
		<版次>一版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.言論集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>078</類號>
		<ISBN>978-986-94308-0-7 (平裝, NT$300, 230面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>國際開放式智慧居家監控系統實習(入門版)</書名>
		<作者>李致中等作</作者>
		<出版單位>安耐美國際智慧節能科技工程</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題>1.智慧型建築 2.監視系統</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>441.39</類號>
		<ISBN>978-986-94306-0-9 (平裝, NT$1800, 732面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>望鄉: 青島的呼喚</書名>
		<作者>許青作</作者>
		<出版單位>采薇</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>855</類號>
		<ISBN>978-986-91487-3-3 (平裝, NT$280, 206面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>地中海上的探戈</書名>
		<作者>周愚著</作者>
		<出版單位>采薇</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>855</類號>
		<ISBN>978-986-91487-4-0 (平裝, NT$250, 214面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>程式設計與生活: 使用C語言</書名>
		<作者>邏輯林編著</作者>
		<出版單位>全華圖書</出版單位>
		<版次>三版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.C(電腦程式語言)</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>312.32C</類號>
		<ISBN>978-986-463-444-6 (平裝附光碟片, 520面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>管理數學</書名>
		<作者>王妙伶等編著</作者>
		<出版單位>全華圖書</出版單位>
		<版次>七版</版次>
		<出版年月>105/12</出版年月>
		<標題>1.管理數學</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>319</類號>
		<ISBN>978-986-463-445-3 (平裝, NT$350, 500面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>男生女生大不同</書名>
		<作者>姜順禮文; iwi圖; 徐鳳擎譯</作者>
		<出版單位>世一</出版單位>
		<版次>初版</版次>
		<出版年月>106/03</出版年月>
		<標題>1.性教育 2.青春期 3.性知識 4.漫畫</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>544.7208</類號>
		<ISBN>978-986-429-278-3 (平裝, 208面, 27公分)</ISBN>
	</Book>
	<Book>
		<書名>讓人好奇的青春期祕密</書名>
		<作者>具聖愛, 金大植, 方明杰文; iwi圖; 徐鳳擎譯</作者>
		<出版單位>世一</出版單位>
		<版次>初版</版次>
		<出版年月>106/03</出版年月>
		<標題>1.性教育 2.青春期 3.性知識 4.漫畫</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>544.7208</類號>
		<ISBN>978-986-429-279-0 (平裝, 208面, 27公分)</ISBN>
	</Book>
	<Book>
		<書名>小小身體真奇妙</書名>
		<作者>姜順禮文; iwi圖; 劉芸譯</作者>
		<出版單位>世一</出版單位>
		<版次>初版</版次>
		<出版年月>106/03</出版年月>
		<標題>1.性教育 2.青春期 3.性知識 4.漫畫</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>544.7208</類號>
		<ISBN>978-986-429-280-6 (平裝, 208面, 27公分)</ISBN>
	</Book>
	<Book>
		<書名>自我保護小常識</書名>
		<作者>具聖愛, 金大植, 方明杰文; iwi圖; 劉芸譯</作者>
		<出版單位>世一</出版單位>
		<版次>初版</版次>
		<出版年月>106/03</出版年月>
		<標題>1.性教育 2.青春期 3.性知識 4.漫畫</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>544.7208</類號>
		<ISBN>978-986-429-281-3 (平裝, 208面, 27公分)</ISBN>
	</Book>
	<Book>
		<書名>易經憨厚學</書名>
		<作者>林東陽著</作者>
		<出版單位>林東君</出版單位>
		<版次></版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-957-43-4262-4 (平裝, 752面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>鑑經(晉商)企業興盛到衰敗</書名>
		<作者>劉燁原著</作者>
		<出版單位>綜合</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.企業管理 2.謀略</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>494</類號>
		<ISBN>978-957-800-850-2 (平裝, NT$358, 400面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>康熙王朝大清帝國崛起</書名>
		<作者>高群編著</作者>
		<出版單位>綜合</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.清聖祖 2.傳記</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>627.2</類號>
		<ISBN>978-957-800-851-9 (平裝, NT$348, 400面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>老二哲學厚黑出頭天</書名>
		<作者>高樓編著</作者>
		<出版單位>綜合</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.應用心理學</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>177</類號>
		<ISBN>978-957-800-852-6 (平裝, NT$328, 336面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>(彩圖版)五福臨門招財進寶好運到</書名>
		<作者>玄磯子編著</作者>
		<出版單位>綜合</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.相宅 2.改運法</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>294.2</類號>
		<ISBN>978-957-800-853-3 (平裝, NT$348, 320面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>Proceeding of asia-pacific conference on llife sciences and biological engineering(APLSBE)</書名>
		<作者></作者>
		<出版單位>Higher Education Forum</出版單位>
		<版次></版次>
		<出版年月>106/03</出版年月>
		<標題></標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號></類號>
		<ISBN>978-986-5654-49-8 (平裝, 60面, 29公分)</ISBN>
	</Book>
	<Book>
		<書名>南簡庄聚落生活文化體驗紀實</書名>
		<作者>臺中市梧棲區南簡社區發展協會著</作者>
		<出版單位>中市南簡社區發展協會</出版單位>
		<版次>一版</版次>
		<出版年月>105/12</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-94309-0-6 (平裝, NT$250, 100面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>系統性創新研討會. 2017</書名>
		<作者>饒忻, 李亭林作</作者>
		<出版單位>中華系統性創新學會</出版單位>
		<版次></版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號></類號>
		<ISBN>978-986-93880-1-6 (平裝附光碟片, NT$500, 150面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>臺北藝術家群像</書名>
		<作者>陳明聰作</作者>
		<出版單位>靜慮藝術</出版單位>
		<版次></版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號></類號>
		<ISBN>978-986-93053-1-0 (平裝, 148面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>臺灣學術性辭典與百科全書類工具書發展策略</書名>
		<作者>鄭桓雄總編輯</作者>
		<出版單位>國家教育研究院</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題></標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號></類號>
		<ISBN>978-986-05-1691-3 (PDF)</ISBN>
	</Book>
	<Book>
		<書名>這個腐女子不得了: 津々井小姐的無節操日常</書名>
		<作者>津々井著; 余瑞芸譯</作者>
		<出版單位>智富</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-93697-2-5 (平裝, NT$260, 192面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>五旬節全備的祝福</書名>
		<作者>慕安得烈(Andrew Murray)著; 王環苓譯</作者>
		<出版單位>錫安堂出版</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.基督教 2.聖靈 3.信仰 4.Holy Spirit 5.234/.1</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>242.15</類號>
		<ISBN>978-986-6577-20-8 (平裝, 178面, 20公分)</ISBN>
	</Book>
	<Book>
		<書名>川語錄</書名>
		<作者>張慧男編</作者>
		<出版單位>金牛頓藝術科技</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-88779-2-4 (精裝, NT$260, 285面, 14公分)</ISBN>
	</Book>
	<Book>
		<書名>企業管理(適用管理概論)滿分必殺絕技</書名>
		<作者>楊均編著</作者>
		<出版單位>千華數位文化</出版單位>
		<版次>第二版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號></類號>
		<ISBN>978-986-374-923-3 (平裝, 536面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>鎮邪甲冑: 劍獅</書名>
		<作者>BARZ作</作者>
		<出版單位>尖端</出版單位>
		<版次>1版</版次>
		<出版年月>106/03</出版年月>
		<標題></標題>
		<適讀對象>青少年</適讀對象>
		<類號></類號>
		<ISBN>978-957-10-7261-6 (第5冊:平裝, 192面, 18公分)</ISBN>
	</Book>
	<Book>
		<書名>挺扁文存與義士臉譜: 現在是還給陳水扁公道的時後!</書名>
		<作者>葉柏祥主編</作者>
		<出版單位>費邊社文創</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-92373-9-0 (平裝, NT$350, 352面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>織境.之境</書名>
		<作者>張瑛玲作</作者>
		<出版單位>樹德科大流設系</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號></類號>
		<ISBN>978-986-93069-8-0 (平裝, NT$850, 64面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>夜郎迷蹤全集. 卷一: 貝葉殘經.蠻書奇譚</書名>
		<作者>凍月滿天著</作者>
		<出版單位>普天</出版單位>
		<版次>第1版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-389-286-1 (平裝, NT$380, 544面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>高普特考試題大補帖: 通訊與系統(含通信系統概要)三、四等. 2017(99-105試題)</書名>
		<作者>項揚, 余宏編著</作者>
		<出版單位>鼎茂圖書</出版單位>
		<版次>一版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號></類號>
		<ISBN>978-986-345-311-6 (平裝, NT$350, 360面, 24公分)</ISBN>
	</Book>
	<Book>
		<書名>金牌店員內部培訓手冊</書名>
		<作者>陳宇梓編著</作者>
		<出版單位>憲業企管</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-369-054-2 (平裝, NT$420, 339面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>土地登記精修(含土地登記實務)</書名>
		<作者>曾韋豪編授</作者>
		<出版單位>大龍海文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-283-157-1 (平裝, NT$550, 864面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>各國人事制度精修</書名>
		<作者>張祺明編授</作者>
		<出版單位>大龍海文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-283-158-8 (平裝, NT$350, 352面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>喵色可餐</書名>
		<作者>千流著; 佩喵繪</作者>
		<出版單位>長鴻</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>青少年</適讀對象>
		<類號></類號>
		<ISBN>978-986-474-265-3 (第3冊:平裝, NT$190, 256面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>孩童戰爭SP特別篇</書名>
		<作者>楊寒作</作者>
		<出版單位>長鴻</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>青少年</適讀對象>
		<類號></類號>
		<ISBN>978-986-474-266-0 (平裝, NT$190, 256面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>青青客色 戀戀楊梅</書名>
		<作者>王淑貞等編輯</作者>
		<出版單位>桃市楊梅國中</出版單位>
		<版次></版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號></類號>
		<ISBN>978-986-05-1692-0 (精裝, NT$350, 25面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>主題式經濟學測驗題庫Q&amp;A</書名>
		<作者>許偉編著</作者>
		<出版單位>志光教育文化</出版單位>
		<版次>第二版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-472-344-7 (平裝, NT$360, 378面, 24公分)</ISBN>
	</Book>
	<Book>
		<書名>高分英文測驗(國民營)</書名>
		<作者>顏弘編著</作者>
		<出版單位>志光教育文化</出版單位>
		<版次>二版</版次>
		<出版年月>105/12</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-472-345-4 (平裝, NT$550, 528面, 24公分)</ISBN>
	</Book>
	<Book>
		<書名>基本電學(國民營考試專用)</書名>
		<作者>鄭奇編著</作者>
		<出版單位>志光教育文化</出版單位>
		<版次></版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-472-346-1 (平裝, NT$500, 480面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>基本電學大意(初等考專用)</書名>
		<作者>鄭奇編著</作者>
		<出版單位>志光教育文化</出版單位>
		<版次></版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-472-347-8 (平裝, NT$500, 480面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>電子學大意(初等考專用)</書名>
		<作者>鄭奇編著</作者>
		<出版單位>志光教育文化</出版單位>
		<版次></版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>
		<ISBN>978-986-472-348-5 (平裝, NT$550, 640面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>旗開得勝國中數學段考題庫講義. 四</書名>
		<作者>張信堂等編著</作者>
		<出版單位>建弘</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>青少年</適讀對象>
		<類號></類號>
		<ISBN>978-986-94310-0-2 (平裝, 144面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>國中數學一回一重點. 幾何基礎篇</書名>
		<作者>劉博義編著</作者>
		<出版單位>建弘</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>青少年</適讀對象>
		<類號></類號>
		<ISBN>978-986-94310-1-9 (第4冊:平裝, 300面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>消失中的漁村風貌</書名>
		<作者>王啟仁著</作者>
		<出版單位>苗縣萬善祠管委會</出版單位>
		<版次></版次>
		<出版年月>106/01</出版年月>
		<標題>1.方志 2.苗栗縣後龍鎮</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>733.9/113.9/119.1</類號>
		<ISBN>978-986-92285-1-0 (平裝, 136面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>柴山少年安魂曲</書名>
		<作者>胡長松著</作者>
		<出版單位>草根</出版單位>
		<版次>二版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>857.7</類號>
		<ISBN>978-986-6656-57-6 (平裝, NT$300, 256面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>(圖文版)老子無為而治.精采故事</書名>
		<作者>玄磯子原著</作者>
		<出版單位>綜合</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.老子 2.研究考訂</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>121.317</類號>
		<ISBN>978-957-800-854-0 (平裝, NT$299, 320面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>北門區志</書名>
		<作者>楊貴三等撰稿; 連慧珠計畫主持</作者>
		<出版單位>南市北門區公所</出版單位>
		<版次>第一版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.方志 2.臺南市北門區</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>733.9/129.9/115.1</類號>
		<ISBN>978-986-05-1693-7 (精裝, NT$1000, 650面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>(圖文並茂)張居正帝鑒圖說</書名>
		<作者>張居正原典; 玄磯子編釋</作者>
		<出版單位>綜合</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.帝範 2.領導論</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>196.267</類號>
		<ISBN>978-957-800-855-7 (平裝, NT$378, 496面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>(經典珍藏版)金匱要略新義</書名>
		<作者>(東漢)張仲景原著; 陳修園集註</作者>
		<出版單位>綜合</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.金匱要略 2.研究考訂</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>413.31</類號>
		<ISBN>978-957-800-856-4 (平裝, NT$328, 336面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>行銷學</書名>
		<作者>林建煌著</作者>
		<出版單位>林建煌</出版單位>
		<版次>五版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.行銷學</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>496</類號>
		<ISBN>978-957-43-4263-1 (平裝, 464面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>未央歌: 臺灣商務印書館70週年紀念版</書名>
		<作者>鹿橋作</作者>
		<出版單位>臺灣商務</出版單位>
		<版次>臺灣五版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>857.7</類號>
		<ISBN>978-957-05-3070-4 (平裝, NT$550, 800面, 22公分)</ISBN>
	</Book>
	<Book>
		<書名>一探究竟!臺灣與日本不動產仲介制度</書名>
		<作者>何彥陞主編</作者>
		<出版單位>何彥陞</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.不動產經紀業 2.比較研究 3.臺灣 4.日本</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>554.89</類號>
		<ISBN>978-957-43-4264-8 (平裝, NT$320, 300面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>運動管理學導論</書名>
		<作者>程紹同等著</作者>
		<出版單位>華泰</出版單位>
		<版次>四版</版次>
		<出版年月>106/03</出版年月>
		<標題>1.運動 2.體育行政</標題>
		<適讀對象>成人(學術)</適讀對象>
		<類號>528.91</類號>
		<ISBN>978-986-93629-5-5 (平裝, 449面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>&lt;&lt;楞嚴經&gt;&gt;二十五圓通之研究</書名>
		<作者>程思著</作者>
		<出版單位>達摩</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.密教部</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>221.94</類號>
		<ISBN>978-986-90832-6-3 (平裝, NT$400, 260面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>暖東: 兩岸三地創作聯展</書名>
		<作者>林永發主編</作者>
		<出版單位>臺東大學美術系</出版單位>
		<版次></版次>
		<出版年月>105/12</出版年月>
		<標題>1.美術 2.作品集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>902.2</類號>
		<ISBN>978-986-05-1694-4 (平裝, NT$800, 70面, 20X20公分)</ISBN>
	</Book>
	<Book>
		<書名>法國甜點大師不傳之祕: 7大殿堂級甜點大師,180道經典創意甜點,不藏私完全圖解親授!</書名>
		<作者>皮耶.艾曼(Pierre Herme)等著; 楊雯珺譯</作者>
		<出版單位>奇光</出版單位>
		<版次>初版</版次>
		<出版年月>106/03</出版年月>
		<標題>1.點心食譜 2.法國</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>427.16</類號>
		<ISBN>978-986-93688-7-2 (精裝, NT$2000, 648面, 25公分)</ISBN>
	</Book>
	<Book>
		<書名>西班牙大廚的分子料理藝術饗宴</書名>
		<作者>丹尼爾.雷格尼亞(Daniel Negreira)著; 夏荷立, 張小眉譯</作者>
		<出版單位>食為天文創</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.食譜 2.烹飪 3.西班牙</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>427.12</類號>
		<ISBN>978-986-93591-2-2 (平裝, NT$788, 200面, 30公分)</ISBN>
	</Book>
	<Book>
		<書名>神、鬼與地方: 臺南民間信仰與傳說研究論集</書名>
		<作者>謝貴文著</作者>
		<出版單位>春暉</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題>1.民間信仰 2.民間文學 3.文集</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>271.907</類號>
		<ISBN>978-986-5798-96-3 (平裝, NT$350, 370面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>國家考試第二類計算機使用指南</書名>
		<作者>黃克紹作</作者>
		<出版單位>詹氏</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.電腦 2.考試指南</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>312</類號>
		<ISBN>978-957-705-529-3 (平裝, NT$380, 212面, 25公分)</ISBN>
	</Book>
	<Book>
		<書名>浪浪不哭: 屬於毛孩子的23個讓你忍不住掉淚的重生故事</書名>
		<作者>大城莉莉, 楊懷民, Vincent Chang作</作者>
		<出版單位>四塊玉文創</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.犬 2.通俗作品</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>437.35</類號>
		<ISBN>978-986-94212-2-5 (平裝, NT$250, 192面, 23公分)</ISBN>
	</Book>
	<Book>
		<書名>新北市學生美展專輯. 105學年度</書名>
		<作者>龔雅雯總編輯</作者>
		<出版單位>新北市政府</出版單位>
		<版次></版次>
		<出版年月>105/12</出版年月>
		<標題>1.美術 2.作品集</標題>
		<適讀對象>兒童(6-12)</適讀對象>
		<類號>902.33</類號>
		<ISBN>978-986-05-1695-1 (平裝, NT$260, 192面, 25公分)</ISBN>
	</Book>
	<Book>
		<書名>別叫我小屁孩,我可以自己來: 專屬青春的完全生存手記</書名>
		<作者>南琦著</作者>
		<出版單位>好優文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.青少年心理 2.自我實現 3.親職教育</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>173.2</類號>
		<ISBN>978-986-93615-7-6 (平裝, NT$320, 256面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>神奇的酵素: 健康活力的必備來源</書名>
		<作者>邱旭祥著</作者>
		<出版單位>曲嘉屋</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.健康食品 2.酵素</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>411.373</類號>
		<ISBN>978-986-91116-4-5 (平裝, NT$220, 128面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>國際財務管理</書名>
		<作者>徐俊明, 黃原桂著</作者>
		<出版單位>新陸</出版單位>
		<版次>二版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.財務管理 2.國際企業</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>494.7</類號>
		<ISBN>978-986-5761-95-0 (平裝, NT$620, 552面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>比星河更遠: 北二區學生聯合文學獎作品集. 2016</書名>
		<作者>周美慧, 陳謙主編</作者>
		<出版單位>景深空間設計</出版單位>
		<版次>一版</版次>
		<出版年月>105/12</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>830.86</類號>
		<ISBN>978-986-91025-6-8 (平裝, NT$170, 144面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>校史人物系列: 黃煌煇校長</書名>
		<作者>陳政宏總編輯</作者>
		<出版單位>成大博物館</出版單位>
		<版次></版次>
		<出版年月>106/01</出版年月>
		<標題>1.黃煌煇 2.校長 3.臺灣傳記</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>783.3886</類號>
		<ISBN>978-986-05-1696-8 (平裝, NT$350, 64面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>金融趨勢大未來</書名>
		<作者>劉宗聖作</作者>
		<出版單位>商訊文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題>1.金融業 2.金融管理 3.臺灣</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>561.933</類號>
		<ISBN>978-986-5812-57-7 (平裝, NT$300, 208面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>伊人難為二部曲. 10, 討債不忘加利息</書名>
		<作者>銀千羽著</作者>
		<出版單位>耕林</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題></標題>
		<適讀對象>青少年</適讀對象>
		<類號>857.7</類號>
		<ISBN>978-986-286-714-3 (平裝, NT$250, 272面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>失智症服務個案彙編</書名>
		<作者>李光廷等作</作者>
		<出版單位>老人福利推動聯盟</出版單位>
		<版次>初版</版次>
		<出版年月>105/12</出版年月>
		<標題>1.老年失智症 2.老人養護 3.個案研究</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>415.9341</類號>
		<ISBN>978-986-91553-1-1 (平裝, NT$150, 81面, 26公分)</ISBN>
	</Book>
	<Book>
		<書名>德蘭修女沉思錄(封聖紀念版)</書名>
		<作者>德蘭修女(Mather Teresa)作; 劉宏信譯</作者>
		<出版單位>心靈工坊文化</出版單位>
		<版次>初版</版次>
		<出版年月>106/02</出版年月>
		<標題>1.天主教 2.信仰 3.靈修</標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號>242.42</類號>
		<ISBN>978-986-357-086-8 (平裝, NT$280, 244面, 21公分)</ISBN>
	</Book>
	<Book>
		<書名>乘風而騎: 九大路線無敵精彩</書名>
		<作者>高雄市政府觀光局[作]</作者>
		<出版單位>高市觀光局</出版單位>
		<版次>初版</版次>
		<出版年月>106/01</出版年月>
		<標題></標題>
		<適讀對象>成人(一般)</適讀對象>
		<類號></類號>